src/Entity/Notification.php
<?php

namespace App\Entity;

use App\Repository\NotificationRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=NotificationRepository::class)
 */
class Notification
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=240)
     */
    private $title;

    /**
     * @ORM\Column(type="text")
     */
    private $content;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $views;

    /**
     * @ORM\Column(type="datetime")
     */
    private $date_created;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getContent(): ?string
    {
        return $this->content;
    }

    public function setContent(string $content): self
    {
        $this->content = $content;

        return $this;
    }

    public function getViews(): ?int
    {
        return $this->views;
    }

    public function setViews(?int $views): self
    {
        $this->views = $views;

        return $this;
    }

    public function getDateCreated(): ?\DateTimeInterface
    {
        return $this->date_created;
    }

    public function setDateCreated(\DateTimeInterface $date_created): self
    {
        $this->date_created = $date_created;

        return $this;
    }
}

src/Controller/AdminNotificationsController.php
<?php

namespace App\Controller;

use App\Entity\Notification;
use App\Form\NotificationType;
use Doctrine\Persistence\ManagerRegistry;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Routing\Annotation\Route;

class AdminNotificationsController extends AbstractController
{
    /**
     * @Route("/admin/notifications", name="app_admin_notifications")
     */
    public function index(ManagerRegistry $doctrine): Response
    {
        $this->denyAccessUnlessGranted('IS_AUTHENTICATED');

        $notifications = $doctrine->getRepository(Notification::class)->findAll();

        return $this->render('admin_notifications/index.html.twig', [
            'notifications' => $notifications
        ]);
    }

    /**
     * @Route("/admin/notification/create", name="app_admin_notification_create")
     */
    public function new(ManagerRegistry $doctrine, Request $request): Response
    {
        $this->denyAccessUnlessGranted('IS_AUTHENTICATED');

        $notification = new Notification();
        $notification->setDateCreated(new \DateTime());

        $form = $this->createForm(NotificationType::class, $notification);
        $form->handleRequest($request);
        if ($form->isSubmitted() && $form->isValid()) {
            $notification = $form->getData();
            $doctrine->getRepository(Notification::class)->add($notification, true);

            return $this->redirectToRoute('app_admin_notifications');
        }

        return $this->render('admin_notifications/edit.html.twig', [
            'form' => $form->createView()
        ]);
    }

    /**
     * @Route("/admin/notification/edit/{id}", name="app_admin_notification_edit")
     */
    public function edit(int $id, ManagerRegistry $doctrine, Request $request): Response
    {
        $this->denyAccessUnlessGranted('IS_AUTHENTICATED');

        $notification = $doctrine->getRepository(Notification::class)->find($id);

        $form = $this->createForm(NotificationType::class, $notification);
        $form->handleRequest($request);
        if ($form->isSubmitted() && $form->isValid()) {
            $em = $doctrine->getManager();
            $notification = $form->getData();
            $em->persist($notification);
            $em->flush();

            return $this->redirectToRoute('app_admin_notifications');
        }

        return $this->render('admin_notifications/edit.html.twig', [
            'form' => $form->createView(),
            'id' => $id
        ]);
    }

    /**
     * @Route("/admin/notification/delete/{id}", name="app_admin_notification_delete")
     */
    public function delete(int $id, ManagerRegistry $doctrine): Response
    {
        $this->denyAccessUnlessGranted('IS_AUTHENTICATED');

        $rep = $doctrine->getRepository(Notification::class);

        $notification = $rep->find($id);
        $rep->remove($notification, true);

        return $this->redirectToRoute('app_admin_notifications');
    }
}

templates/admin_notifications/edit.html.twig
{% extends 'base.html.twig' %}
{% form_theme form 'bootstrap_5_layout.html.twig' %}

{% block title %}Create new notification{% endblock %}

{% block body %}
	<div class="d-grid gap-2 d-md-flex justify-content-between align-items-center">
		<h1 class="display-5">{% if id is defined %}Edit notification #{{ id }}{% else %}Create new notification{% endif %}</h1>
		<ul class="nav">
			<li class="nav-item"><a href="{{ path('app_admin_notifications') }}" class="nav-link" tabindex="-1">Go to the list</a></li>
		</ul>
	</div>
	{{ form(form) }}
{% endblock %}

templates/admin_notifications/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Notifications list{% endblock %}

{% block body %}
    <div class="d-grid gap-2 d-md-flex justify-content-between align-items-center">
        <h1 class="display-5">Notifications editor</h1>
        <div class="d-grid gap-2 d-md-flex justify-content-end align-items-center">
            <a href="{{ path('app_admin_notification_create') }}" class="btn btn-success" tabindex="-1" role="button">Create new</a>
            <a href="{{ path('app') }}" class="btn btn-success" tabindex="-1" role="button">Show on page</a>
        </div>
    </div>
    <table class="table border editor-table">
        <thead>
        <tr>
            <th scope="col">ID</th>
            <th scope="col">Title</th>
            <th scope="col">Text</th>
            <th scope="col">Views</th>
            <th scope="col">Created</th>
            <th scope="col">Actions</th>
        </tr>
        </thead>
        <tbody>
        {% for row in notifications %}
        <tr>
            <th scope="row">{{ row.id }}</th>
            <td>{{ row.title }}</td>
            <td>{{ row.content }}</td>
            <td>{{ row.views|number_format }}</td>
            <td>{{ row.dateCreated|date("d.m.Y H:i") }}</td>
            <td>
                <form action="{{ path('app_admin_notification_delete', {id: row.id} ) }}" class="delete-form row g-2">
                    <div class="col-auto"><a href="{{ path('app_admin_notification_edit', {id: row.id} ) }}" class="btn btn-primary" tabindex="-1" role="button">Edit</a></div>
                    <div class="col-auto"><button type="submit" class="btn btn-danger">Delete</button></div>
                </form>
            </td>
        </tr>
        {% endfor %}
        </tbody>
    </table>
{% endblock %}
{% block pagescripts %}
<script src="{{ asset('js/admin.js') }}"></script>
{% endblock %}